version: '3'
services:
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: centos7
    volumes:
    - "$PWD/aws-s3.sh:/tmp/script.sh"
    - "$PWD/centos7/scripts:/var/scripts"
    - "$PWD/jenkins_home:/var/jenkins_home"
    - "$PWD/db_data:/var/lib/mysql"
    networks:
        - net
    ports:
    - "22:50000"
  web:
    container_name: web
    image: ansible-web
    build:
      context: jenkins-ansible/web
    ports:
      - "80:80"
    networks:
      - net
  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net
  jenkins:
    container_name: jenkins
    image: jenkins-ansible
    build:
      context: jenkins-ansible
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - net
    command: bash -c "/usr/local/bin/jenkins.sh && /tmp/initial-script.sh"
networks:
    net:
